In [3]:
# import the pandas
import pandas as pd
import numpy as np

nan

pandas is just like a dict of the numpy, and we can named the different dimension.

In [15]:
# a array in pandas
s = pd.Series([1, 3, 5, np.nan, 44, 1])

# index and number, also show the type
print(s)

0     1.0
1     3.0
2     5.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [14]:
# a matrix in pandas (dataframe)
dates = pd.date_range('20160101', periods=6)
print(dates)

# index default is number (0, 1, ...), but we use the index we created (dates)
# index and columns can be created before
df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns=['a', 'b', 'c', 'd'])
print(df)

# defualt use number from zero to index
df2 = pd.DataFrame(np.random.rand(6,4))
print(df2)

# we can also use dict to create dataframe
# or import from numpy

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')
                   a         b         c         d
2016-01-01  1.259086  0.173645 -0.496698  0.781653
2016-01-02 -2.308323  0.005400  0.329517 -0.695501
2016-01-03  0.524288  0.138693 -0.048773  0.576691
2016-01-04 -0.319599 -0.033846  0.395082  1.055901
2016-01-05  0.833756 -1.015946  0.409716  0.880464
2016-01-06  0.850031 -0.253158  0.435153  1.077864
          0         1         2         3
0  0.360105  0.640561  0.880581  0.873057
1  0.289805  0.903418  0.982025  0.029698
2  0.631548  0.704561  0.818059  0.454087
3  0.311996  0.963946  0.988691  0.744063
4  0.402752  0.835969  0.230570  0.987275
5  0.516988  0.064411  0.717684  0.481174


In [17]:
print(df.dtypes)   # show the columns' dtypes

a    float64
b    float64
c    float64
d    float64
dtype: object


In [21]:
print(df.index ,'\n', df.columns)    # get the index and columns

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D') 
 Index(['a', 'b', 'c', 'd'], dtype='object')


In [23]:
print(df.values)

[[ 1.2590863   0.17364488 -0.49669767  0.78165266]
 [-2.3083231   0.00539995  0.32951701 -0.69550103]
 [ 0.52428822  0.13869276 -0.04877341  0.5766909 ]
 [-0.31959853 -0.03384613  0.39508164  1.05590148]
 [ 0.83375553 -1.01594592  0.40971616  0.88046418]
 [ 0.85003133 -0.25315836  0.43515282  1.07786435]]


In [25]:
df.describe()    # calculate the number, ignore the date and other data types 

a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean   0.139873 -0.164202  0.170666  0.612845
std    1.310800  0.443852  0.373155  0.667193
min   -2.308323 -1.015946 -0.496698 -0.695501
25%   -0.108627 -0.198330  0.045799  0.627931
50%    0.679022 -0.014223  0.362299  0.831058
75%    0.845962  0.105370  0.406058  1.012042
max    1.259086  0.173645  0.435153  1.077864

In [30]:
df.T    # transpose

2016-01-01  2016-01-02  2016-01-03  2016-01-04  2016-01-05  2016-01-06
a    1.259086   -2.308323    0.524288   -0.319599    0.833756    0.850031
b    0.173645    0.005400    0.138693   -0.033846   -1.015946   -0.253158
c   -0.496698    0.329517   -0.048773    0.395082    0.409716    0.435153
d    0.781653   -0.695501    0.576691    1.055901    0.880464    1.077864

In [36]:
df.sort_index(axis=0, ascending=False)    # sort the index, 0 - index, 1 - columns

a         b         c         d
2016-01-06  0.850031 -0.253158  0.435153  1.077864
2016-01-05  0.833756 -1.015946  0.409716  0.880464
2016-01-04 -0.319599 -0.033846  0.395082  1.055901
2016-01-03  0.524288  0.138693 -0.048773  0.576691
2016-01-02 -2.308323  0.005400  0.329517 -0.695501
2016-01-01  1.259086  0.173645 -0.496698  0.781653

In [41]:
df.sort_values(by='a')    # sort the value in the dataframe

a         b         c         d
2016-01-02 -2.308323  0.005400  0.329517 -0.695501
2016-01-04 -0.319599 -0.033846  0.395082  1.055901
2016-01-03  0.524288  0.138693 -0.048773  0.576691
2016-01-05  0.833756 -1.015946  0.409716  0.880464
2016-01-06  0.850031 -0.253158  0.435153  1.077864
2016-01-01  1.259086  0.173645 -0.496698  0.781653

## select the data

In [52]:
dates = pd.date_range('20160101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index=dates, columns=['A', 'B', 'C', 'D'])
print(df)

             A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15
2016-01-05  16  17  18  19
2016-01-06  20  21  22  23


In [57]:
# choose columns
print('choose columns\n', df['A'], '\n', df.A)

# choose with slice
print('choose index\n', df[0:3], '\n', df['2016-01-01':'2016-01-03'])

# choose with label: loc for index (location)
print(df.loc['2016-01-02'])

# choose with label: loc for columns
print(df.loc[:, ['A', 'B']])

choose columns
 2016-01-01     0
2016-01-02     4
2016-01-03     8
2016-01-04    12
2016-01-05    16
2016-01-06    20
Freq: D, Name: A, dtype: int64 
 2016-01-01     0
2016-01-02     4
2016-01-03     8
2016-01-04    12
2016-01-05    16
2016-01-06    20
Freq: D, Name: A, dtype: int64
choose index
             A  B   C   D
2016-01-01  0  1   2   3
2016-01-02  4  5   6   7
2016-01-03  8  9  10  11 
             A  B   C   D
2016-01-01  0  1   2   3
2016-01-02  4  5   6   7
2016-01-03  8  9  10  11
A    4
B    5
C    6
D    7
Name: 2016-01-02 00:00:00, dtype: int64
             A   B
2016-01-01   0   1
2016-01-02   4   5
2016-01-03   8   9
2016-01-04  12  13
2016-01-05  16  17
2016-01-06  20  21


In [60]:
print(df[0:1])

            A  B  C  D
2016-01-01  0  1  2  3
